version: '3'

services:
  db:
    image: postgres:9.6
  rest:
    build: .
    command: ["bash", "wait-for-postgresql.sh", "db", "bash", "entrypoint.sh"]
    volumes:
      - .:/code
    ports:
      - "8080:8000"
    depends_on:
      - db
