# Generated by Django 2.1.7 on 2019-04-08 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordStatistic',
            fields=[
                ('word_of_intrest', models.TextField(primary_key=True, serialize=False)),
                ('occurance_count', models.IntegerField()),
            ],
            options={
                'ordering': ['-occurance_count'],
            },
        ),
    ]
